// Odmoria — engleski rječnik sučelja DOMAĆINA (vidi domacin-jezik.js).
// Ključ = hrvatski tekst točno kako ga stranica prikaže (razmaci sažeti).
// P = uzorci s promjenjivim dijelom: {} redom, ili {1}, {2}… kad engleski
// mijenja redoslijed. Novi tekst u sučelju = novi red ovdje; bez njega ostaje
// hrvatski (ne pukne). Prijevode gostinskih stranica drži jezici.js.

export const T = {
  "(bez datuma rođenja računa se kao odrasla osoba)": "(without a date of birth counted as an adult)",
  ")\">Vrati automatski": ")\">Restore automatic",
  "+ Dodaj": "+ Add",
  "+ Dodaj atrakciju": "+ Add attraction",
  "+ Dodaj mjesto": "+ Add place",
  "+ Dodaj pitanje": "+ Add question",
  "+ Dodaj pravilo": "+ Add rule",
  "+ Dodaj prijevoz": "+ Add transport",
  "+ Nova rezervacija": "+ New booking",
  "+ dolazak isti dan": "+ same-day arrival",
  ", ali popunjavanje praznina je uključeno": ", but gap filling is switched on",
  ", bilo koji budući datum i CVC.": ", any future date and CVC.",
  ", bilo koji budući datum i bilo koji CVC.": ", any future date and any CVC.",
  ", domaćin": ", host",
  ". Link vrijedi ograničeno vrijeme.": ". The link is valid for a limited time.",
  ". Ostavite prazno pa se izvede iz površine ili broja gostiju.": ". Leave empty and it's derived from the size or number of guests.",
  "/ noć": "/ night",
  "/god": "/yr",
  "/mj": "/mo",
  "/mj mjesečno": "/mo monthly",
  "0% provizije na rezervacije.": "0% commission on bookings.",
  "1 objekt": "1 property",
  "1 objekt · Besplatno": "1 property · Free",
  "12 mjeseci": "12 months",
  "15 min hoda": "15 min walk",
  "2 odrasle": "2 adults",
  "22 m², kamin": "22 m², fireplace",
  "30 dana": "30 days",
  "32° · Temperatura bazena": "32° · Pool temperature",
  "5 fotografija po objektu": "5 photos per property",
  "8 min hoda": "8 min walk",
  "90 dana": "90 days",
  ": greška": ": error",
  "; ništa se ne briše, a iste stavke se ne ponavljaju. Šifra vrata, Wi-Fi i adresa se nikad ne prenose.": "; nothing is deleted and identical items aren't repeated. The door code, Wi-Fi and address are never copied.",
  "? Više ga nećete vidjeti dok vas vlasnik ponovno ne pozove.": "? You won't see it again until the owner invites you again.",
  "Adresa": "Address",
  "Adresa objekta": "Property address",
  "Airbnb": "Airbnb",
  "Airbnb → Kalendar → Dostupnost → Poveži kalendare → Uvezi kalendar.": "Airbnb → Calendar → Availability → Connect calendars → Import calendar.",
  "Ako postoji račun s tom adresom, poslali smo link za novu lozinku": "If there's an account with that address, we've sent a link for a new password",
  "Ako upišete e-mail, gost sam dobije link 3 dana prije dolaska i zahvalu s molbom za ocjenu na dan odlaska; e-mail se briše 30 dana nakon odlaska. Telefon služi samo za slanje odavde i ne sprema se.": "If you enter an e-mail, the guest automatically gets the link 3 days before arrival and a thank-you with a request for a rating on the day of departure; the e-mail is deleted 30 days after departure. The phone is used only to send from here and isn't saved.",
  "Aktivan": "Active",
  "Analitika": "Analytics",
  "Aparat za kavu": "Coffee machine",
  "Apartman": "Apartment",
  "Atrakcije": "Attractions",
  "Atrakcije i aktivnosti": "Attractions and activities",
  "Atrakcije i izleti": "Attractions and trips",
  "Automatska sinkronizacija očito ne radi (ili još nije uključena) — nove rezervacije s platformi ne vide se dok ne sinkronizirate.": "Automatic sync clearly isn't working (or isn't switched on yet) — new bookings from the platforms won't show until you sync.",
  "Automatske provjere kalendara, linkova za goste i vodiča.": "Automatic checks of the calendar, guest links and the guide.",
  "Automatski e-mail gostima": "Automatic e-mails to guests",
  "Automatski e-mail gostima je isključen": "Automatic e-mails to guests are off",
  "Automatski e-mail gostima je uključen": "Automatic e-mails to guests are on",
  "Automatski prijevod": "Automatic translation",
  "Automatski prijevod nije uključen (ANTHROPIC_API_KEY) — tekst možete prevesti sami.": "Automatic translation isn't switched on (ANTHROPIC_API_KEY) — you can translate the text yourself.",
  "Balkon / Terasa": "Balcony / Terrace",
  "Baza još nema stupce za temu. Pokrenite sql/add-theme-to-properties.sql u Supabase SQL editoru, pa ponovno spremite.": "The database doesn't have the theme columns yet. Run sql/add-theme-to-properties.sql in the Supabase SQL editor, then save again.",
  "Bazen": "Pool",
  "Besplatno": "Free",
  "Besplatno za početak · bez kartice": "Free to start · no card",
  "Beton": "Concrete",
  "Bez naziva": "Untitled",
  "Booking": "Booking",
  "Booking / Airbnb (zaključano)": "Booking / Airbnb (locked)",
  "Booking Extranet → Cijene i dostupnost → Sinkronizacija kalendara → Uvezi kalendar.": "Booking Extranet → Rates & availability → Sync calendars → Import calendar.",
  "Booking.com": "Booking.com",
  "Boravaka": "Stays",
  "Boravci": "Stays",
  "Boravci ove godine": "Stays this year",
  "Boravi": "Staying",
  "Boravišna pristojba": "Tourist tax",
  "Borova šuma": "Pine forest",
  "Brisanje računa": "Delete account",
  "Brišem…": "Deleting…",
  "Broj isprave": "Document number",
  "Broj čistačice": "Cleaner's number",
  "Broj, duljina i gruba procjena prihoda.": "Number, length and a rough revenue estimate.",
  "Business": "Business",
  "Chalet": "Chalet",
  "Check-in i Wi-Fi": "Check-in and Wi-Fi",
  "Check-in od": "Check-in from",
  "Check-in od —": "Check-in from —",
  "Check-in podaci spremljeni ✓": "Check-in details saved ✓",
  "Check-out do": "Check-out until",
  "Check-out mora biti nakon check-in.": "Check-out must be after check-in.",
  "Cijela analitika": "Full analytics",
  "Cijena": "Price",
  "Cijena boravka": "Price of stay",
  "Cijena po noćenju": "Price per night",
  "Cijena po noćenju u eurima": "Price per night in euros",
  "Cijena po noći (€)": "Price per night (€)",
  "Cijena spremljena ✓": "Price saved ✓",
  "Cijene i sadržaji": "Prices and amenities",
  "Dajte vodiču osobni ton.": "Give the guide a personal touch.",
  "Dalje →": "Next →",
  "Dan": "Day",
  "Dashboard — Odmoria": "Dashboard — Odmoria",
  "Datum je sinkroniziran s Booking/Airbnb — mijenja se automatski 🔒": "This date is synced with Booking/Airbnb — it changes automatically 🔒",
  "Datum rođenja": "Date of birth",
  "Deaktiviraj": "Deactivate",
  "Deaktiviraj link?": "Deactivate the link?",
  "Detalji": "Details",
  "Dijelovi objekta": "Property sections",
  "Dizalo": "Lift",
  "Dnevni boravak": "Living room",
  "Dnevni prostor": "Living space",
  "Dobra": "Good",
  "Dobro došli": "Welcome",
  "Dobro došli natrag.": "Welcome back.",
  "Dobro došli u naš apartman!": "Welcome to our apartment!",
  "Dobro došli. Ovdje vas čekaju sve privatne informacije za boravak.": "Welcome. All the private information for your stay is here.",
  "Dobrodošlica i domaćin": "Welcome and host",
  "Dodaj objekt": "Add property",
  "Dodaj odabrano": "Add selected",
  "Dodajem…": "Adding…",
  "Dodajte fotografije": "Add photos",
  "Dodajte korisne načine kretanja i kontakte.": "Add useful ways to get around and contacts.",
  "Dodajte novi objekt": "Add a new property",
  "Dodajte objekt — Odmoria": "Add a property — Odmoria",
  "Dodano ✓": "Added ✓",
  "Dok ne sinkronizirate, zauzeti termini s platformi ne vide se ni vama ni gostima.": "Until you sync, dates booked on the platforms aren't visible to you or your guests.",
  "Dolasci i odlasci iz kalendara, s Bookinga, Airbnba i iz vaših rezervacija.": "Arrivals and departures from the calendar, Booking, Airbnb and your bookings.",
  "Dolasci i odlasci za sljedećih 60 dana, s vremenom prijave i odjave. Bez šifri, Wi-Fija i imena gostiju. Stranica je uvijek ažurna.": "Arrivals and departures for the next 60 days, with check-in and check-out times. No codes, Wi-Fi or guest names. The page is always up to date.",
  "Dolazak": "Arrival",
  "Dolazak i upute": "Arrival and instructions",
  "Dolazak, Wi-Fi, kod vrata i kućna pravila.": "Arrival, Wi-Fi, door code and house rules.",
  "Dolazak, Wi-Fi, uređaji, kućna pravila i česta pitanja.": "Arrival, Wi-Fi, appliances, house rules and FAQ.",
  "Dolje": "Down",
  "Domaćin": "Host",
  "Dopuni vodič": "Complete the guide",
  "Dopusti kraći boravak ako popunjava prazninu između dvije rezervacije (neovisno o minimalnom broju noćenja)": "Allow a shorter stay if it fills a gap between two bookings (regardless of the minimum number of nights)",
  "Dosegnuli ste limit trenutnog plana.": "You've reached your current plan's limit.",
  "Dostignut je limit vašeg plana.": "You've reached your plan's limit.",
  "Dostignut limit objekata": "Property limit reached",
  "Dostupno 0–24": "Available 24/7",
  "Dostupno u višem planu": "Available on a higher plan",
  "Dostupnost": "Availability",
  "Dovršenost vodiča": "Guide completeness",
  "Dovršite ove dijelove kako bi vodič bio potpun.": "Complete these sections so the guide is complete.",
  "Drugi datumi…": "Other dates…",
  "Država": "Country",
  "Država prebivališta": "Country of residence",
  "Države posjetitelja": "Visitor countries",
  "Države se još ne bilježe. Kad se u Supabaseu pokrene sql/add-country-to-page-views.sql, svaki novi pregled dobiva državu posjetitelja (bez IP adrese).": "Countries aren't recorded yet. Once sql/add-country-to-page-views.sql is run in Supabase, every new view gets the visitor's country (without the IP address).",
  "Države, kanali upita, što gosti otvaraju, kada gledaju, izvori noćenja i praznine u kalendaru.": "Countries, inquiry channels, what guests open, when they view, where nights come from and calendar gaps.",
  "Državljanstvo": "Citizenship",
  "Dva odvojena prikaza za dvije različite svrhe.": "Two separate views for two different purposes.",
  "E-mail adresa nije ispravna.": "The e-mail address isn't valid.",
  "E-mail gosta": "Guest's e-mail",
  "E-mail ili lozinka nisu točni.": "Wrong e-mail or password.",
  "E-mail je potvrđen": "E-mail confirmed",
  "E-mail još nije potvrđen. Otvorite link iz poruke koju smo vam poslali.": "Your e-mail isn't confirmed yet. Open the link in the message we sent you.",
  "E-mail se ne mijenja ovdje — javite se podršci.": "Your e-mail can't be changed here — contact support.",
  "E-mail za upite": "E-mail for inquiries",
  "E-mailom": "By e-mail",
  "Email za upite": "E-mail for inquiries",
  "Engleski": "English",
  "Facebook grupe": "Facebook groups",
  "Fen za kosu": "Hair dryer",
  "Format slike": "Image format",
  "Fotografija": "Photo",
  "Fotografija obrisana": "Photo deleted",
  "Fotografija po objektu": "Photos per property",
  "Fotografija se nije učitala, pa je pozadina u bojama Odmorije.": "The photo didn't load, so the background uses Odmoria's colours.",
  "Fotografije": "Photos",
  "Fotografije objekta": "Property photos",
  "Fotografije, dostupnost, preporuke. Bez šifri i lozinki — sigurno za društvene mreže i oglase.": "Photos, availability, recommendations. No codes or passwords — safe for social media and ads.",
  "Fotografije, lokacija, sadržaji i preporuke.": "Photos, location, amenities and recommendations.",
  "Free": "Free",
  "Gdje ostavljamo otpad?": "Where do we leave the rubbish?",
  "Gdje tražiti": "Where to search",
  "Generiraj privatni gostinski link za potvrđenog gosta.": "Generate a private guest link for a confirmed guest.",
  "Glavni dijelovi": "Main sections",
  "Glačalo": "Iron",
  "Godišnje": "Yearly",
  "Google Maps pojam": "Google Maps search term",
  "Gore": "Up",
  "Gost": "Guest",
  "Gost još nije upisao podatke. U vodiču ih upisuje pod „Prijava boravka” — link ste mu već poslali.": "The guest hasn't entered their details yet. They do it in the guide under “Stay registration” — you've already sent them the link.",
  "Gost kopira lozinku jednim dodirom — bez tipkanja.": "Guests copy the password with one tap — no typing.",
  "Gost ocjenjuje boravak u vodiču (Odlazak), od dana dolaska. Javne recenzije vide se na vašoj javnoj stranici; svaku možete sakriti.": "Guests rate their stay in the guide (Departure), from the day they arrive. Public reviews appear on your public page; you can hide any of them.",
  "Gost plaća vama. Vi birate alat koji vam odgovara.": "The guest pays you. You choose the tool that suits you.",
  "Gosti": "Guests",
  "Gosti ih šalju s vaše javne stranice. Prihvatite upit — nastane rezervacija, dani se označe kao zauzeti i dobijete link koji odmah pošaljete gostu.": "Guests send them from your public page. Accept an inquiry — a booking is created, the days are marked as booked and you get a link to send the guest straight away.",
  "Gosti na javnoj stranici vide sve termine kao slobodne. Povežite Booking.com ili Airbnb, ili označite zauzete dane.": "Guests on the public page see every date as free. Connect Booking.com or Airbnb, or mark booked days.",
  "Gosti u vodiču": "Guests in the guide",
  "Gosti vam pišu izravno — bez platforme u sredini.": "Guests message you directly — no platform in between.",
  "Gosti ·": "Guests ·",
  "Gosti · čeka podatke": "Guests · waiting for details",
  "Gostinski link kopiran!": "Guest link copied!",
  "Gotova objava": "Ready-made post",
  "Gotova slika i tekst za društvene mreže i oglase, te letak za ispis.": "A ready-made image and text for social media and ads, plus a printable flyer.",
  "Gotovo": "Done",
  "Grad ili mjesto koje gost prepozna.": "A town or place your guest will recognise.",
  "Grad prebivališta": "City of residence",
  "Grafikon": "Chart",
  "Greška": "Error",
  "Greška pri spremanju:": "Error while saving:",
  "Greška:": "Error:",
  "Grijanje": "Heating",
  "Gumb se uključuje tek kad je potvrda upisana točno.": "The button turns on only when the confirmation is typed exactly.",
  "Hladnjak": "Fridge",
  "Ikona (emoji)": "Icon (emoji)",
  "Imate aktivnu pretplatu karticom. Prvo je otkažite (Pretplata i limiti → Upravljaj pretplatom), pa obrišite račun.": "You have an active card subscription. Cancel it first (Subscription and limits → Manage subscription), then delete your account.",
  "Imate nespremljene promjene.": "You have unsaved changes.",
  "Imate više objekata u istoj kući ili mjestu? Kućna pravila, česta pitanja, preporuke i upute ne morate pisati ponovno.": "Several properties in the same house or town? You don't have to write house rules, FAQs, recommendations and instructions again.",
  "Ime": "First name",
  "Ime domaćina": "Host name",
  "Ime gosta (": "Guest name (",
  "Ime i prezime gosta": "Guest's full name",
  "Ime ili uloga": "Name or role",
  "Informacije koje se prikazuju u zaglavlju vodiča.": "Information shown in the guide header.",
  "Informativna cijena za javnu stranicu objekta.": "An indicative price for the property's public page.",
  "Informativna cijena, minimalan boravak i sve što je gostu dostupno.": "Indicative price, minimum stay and everything guests can use.",
  "Instagram": "Instagram",
  "Ispuni obavezno polje": "Fill in the required field",
  "Istaknite aktivnosti i mjesta vrijedna posjeta.": "Highlight activities and places worth visiting.",
  "Istaknite doživljaje zbog kojih vrijedi ostati dan duže.": "Highlight experiences worth staying an extra day for.",
  "Istaknuta brojka": "Highlight figure",
  "Istaknuto": "Highlight",
  "Istekao": "Expired",
  "Isti dan dolazi": "Same-day arrival",
  "Iz objekta": "From property",
  "Izaberite temu koja odlučuje što gost vidi prvo.": "Choose the theme that decides what guests see first.",
  "Izbor se sprema uz vaš račun. E-mailove počinjemo slati kad uključimo slanje pošte.": "Your choice is saved to your account. We'll start sending e-mails once mail delivery is switched on.",
  "Izgled": "Layout",
  "Izgled stranice": "Page look",
  "Izmjena istog dana": "Same-day changeover",
  "Iznos određuje vaša općina/grad. Djeca do 12 godina ne plaćaju, od 12 do 18 plaćaju pola.": "The amount is set by your municipality/town. Children under 12 don't pay, from 12 to 18 they pay half.",
  "Iznos u €": "Amount in €",
  "Izradom računa prihvaćate": "By creating an account you accept the",
  "Izravno (rezervacije u Odmoriji i ručno označeno):": "Direct (bookings in Odmoria and marked manually):",
  "Izvezi boravke (CSV)": "Export stays (CSV)",
  "Izvoz kalendara još nije uključen — u Supabaseu treba pokrenuti": "Calendar export isn't switched on yet — in Supabase you need to run",
  "JPG ili PNG, najviše 5 MB po slici": "JPG or PNG, up to 5 MB per image",
  "JPG, PNG ili WEBP · do 5 MB po fotografiji": "JPG, PNG or WEBP · up to 5 MB per photo",
  "Jaka ✓": "Strong ✓",
  "Jasno postavite kada je objekt spreman.": "Make it clear when the property is ready.",
  "Javite nam se": "Contact us",
  "Javna stranica": "Public page",
  "Javna stranica i privatni vodič": "Public page and private guide",
  "Javna stranica i privatni vodič, na istoj skali.": "Public page and private guide, on the same scale.",
  "Javna stranica, alat za domaćine i privatni vodič — na jednom mjestu.": "A public page, a host tool and a private guide — in one place.",
  "Javni link dijelite svugdje. Privatni link šaljete samo potvrđenom gostu.": "Share the public link everywhere. Send the private link only to a confirmed guest.",
  "Javni link je kopiran.": "Public link copied.",
  "Javni link kopiran!": "Public link copied!",
  "Javni prikaz": "Public view",
  "Javno": "Public",
  "Jezik": "Language",
  "Jezik poruka gostu": "Language of messages to the guest",
  "Još nema ocjena. Gost ocjenu daje u vodiču pod „Odlazak”, od dana dolaska.": "No ratings yet. Guests rate in the guide under “Departure”, from the day they arrive.",
  "Još nema podataka — gosti još nisu otvarali dijelove vodiča u ovom razdoblju.": "No data yet — guests haven't opened parts of the guide in this period.",
  "Još nema rezervacija. Kreiraj prvi gostinski link →": "No bookings yet. Create your first guest link →",
  "Još nema teksta za prijevod. Kad upišete riječ dobrodošlice, upute, pravila ili preporuke, pojavit će se ovdje.": "No text to translate yet. Once you write a welcome, instructions, rules or recommendations, they'll appear here.",
  "Još nije prevedeno": "Not translated yet",
  "Još nije sinkronizirano.": "Not synced yet.",
  "Još ništa dodano.": "Nothing added yet.",
  "Još trenutak, postavljamo vaš račun.": "One moment, we're setting up your account.",
  "Kada gledaju stranicu": "When they view the page",
  "Kada gosti otvaraju vodič": "When guests open the guide",
  "Kafići": "Cafés",
  "Kako gost ulazi": "How guests get in",
  "Kako gost vidi": "How guests see it",
  "Kako gosti vide vaše tekstove na svom jeziku — pregledajte i ispravite prijevod.": "How guests see your texts in their language — review and correct the translation.",
  "Kako plaćate": "How you pay",
  "Kalendar": "Calendar",
  "Kalendar je ažuran, svi nadolazeći gosti imaju link, a vodič ima šifru i Wi-Fi.": "The calendar is up to date, all upcoming guests have a link, and the guide has a code and Wi-Fi.",
  "Kalendar je prazan": "The calendar is empty",
  "Kalendar je prazan, pa ne znamo što je slobodno — upišite datume sami ili povežite Booking/Airbnb (Boravci → iCal).": "The calendar is empty, so we don't know what's free — enter dates yourself or connect Booking/Airbnb (Stays → iCal).",
  "Kalendar je prazan. Označite zauzete dane ili povežite Booking.com i Airbnb (Boravci → iCal).": "The calendar is empty. Mark booked days or connect Booking.com and Airbnb (Stays → iCal).",
  "Kalendar s Bookinga ili Airbnba još nije povučen": "The Booking or Airbnb calendar hasn't been pulled yet",
  "Kapacitet": "Capacity",
  "Kategorija": "Category",
  "Klik na WhatsApp, e-mail ili kopiranje poruke na javnoj stranici.": "Clicks on WhatsApp, e-mail or copying the message on the public page.",
  "Klikni fotografiju da je postaviš kao naslovnu.": "Click a photo to make it the cover.",
  "Klikni prvi i zadnji datum da označiš cijeli period zauzetim.": "Click the first and last date to mark the whole period as booked.",
  "Klima uređaj": "Air conditioning",
  "Klima-uređaj": "Air conditioning",
  "Kod za ulazak": "Entry code",
  "Kod za ulazak postavljen": "Entry code set",
  "Koji dio vodiča gosti najčešće traže.": "Which part of the guide guests look for most.",
  "Koji upiti": "Which inquiries",
  "Kolovoz": "August",
  "Kontakt": "Contact",
  "Kontakt domaćina": "Host contact",
  "Kopiraj": "Copy",
  "Kopiraj javni link": "Copy public link",
  "Kopiraj kao tekst": "Copy as text",
  "Kopiraj link": "Copy link",
  "Kopiraj ponudu": "Copy offer",
  "Kopiraj raspored": "Copy schedule",
  "Kopirana poruka": "Copied message",
  "Kopiranje nije uspjelo": "Copying failed",
  "Kopirano": "Copied",
  "Koraci postavljanja": "Setup steps",
  "Korak 1 od 5 · Naziv i lokacija": "Step 1 of 5 · Name and location",
  "Korak 2 od 5 · Dolazak": "Step 2 of 5 · Arrival",
  "Korak 3 od 5 · Wi-Fi": "Step 3 of 5 · Wi-Fi",
  "Korak 4 od 5 · Fotografije": "Step 4 of 5 · Photos",
  "Korak 5 od 5 · Vaši linkovi": "Step 5 of 5 · Your links",
  "Kratka, jasna očekivanja — jedno pravilo po retku.": "Short, clear expectations — one rule per line.",
  "Kratke informacije za uređaje i sadržaje u objektu.": "Short notes on appliances and amenities in the property.",
  "Kratki slobodni termini između dva boravka u sljedećih 90 dana — teško se popunjavaju sami.": "Short free periods between two stays in the next 90 days — they rarely fill on their own.",
  "Kratko, uz sliku.": "Short, with the image.",
  "Kreiraj link →": "Create link →",
  "Kreveta": "Beds",
  "Kreveti": "Beds",
  "Kuhalo za vodu": "Kettle",
  "Kuhinja": "Kitchen",
  "Kupaonica": "Bathroom",
  "Kupaonice": "Bathrooms",
  "Kuća": "House",
  "Kućna pravila": "House rules",
  "Letak se nije mogao pripremiti:": "The flyer couldn't be prepared:",
  "Letak za ispis": "Printable flyer",
  "Limiti se čitaju iz tablice planova i provodi ih baza.": "Limits are read from the plans table and enforced by the database.",
  "Link deaktiviran": "Link deactivated",
  "Link generiran": "Link created",
  "Link je istekao ili je već iskorišten. Zatražite novi.": "The link has expired or has already been used. Request a new one.",
  "Link je spreman — zalijepite ga u Booking i Airbnb": "The link is ready — paste it into Booking and Airbnb",
  "Link kopiran": "Link copied",
  "Link kopiran!": "Link copied!",
  "Link na vodič 3 dana prije dolaska i zahvala s molbom za ocjenu na dan odlaska — samo gostima kojima ste upisali e-mail.": "The guide link 3 days before arrival and a thank-you with a request for a rating on the day of departure — only to guests whose e-mail you entered.",
  "Link nije valjan": "The link isn't valid",
  "Link za": "Link for",
  "Link za novu lozinku je istekao ili je već iskorišten. Prijavite se ili zatražite novi link.": "The link for a new password has expired or has already been used. Log in or request a new link.",
  "Link za potvrdu je istekao ili je već iskorišten. Registrirajte se ponovno ili se prijavite.": "The confirmation link has expired or has already been used. Sign up again or log in.",
  "Link za čistačicu": "Cleaner link",
  "Link za čistačicu je spreman": "The cleaner link is ready",
  "Link za čistačicu još nije uključen — u Supabaseu treba pokrenuti": "The cleaner link isn't switched on yet — in Supabase you need to run",
  "Linkovi": "Links",
  "Linkovi i QR": "Links and QR",
  "Linkovi objekta": "Property links",
  "Lipanj": "June",
  "Listopad": "October",
  "Ljekarna": "Pharmacy",
  "Ljubimci dozvoljeni": "Pets allowed",
  "Lokacija": "Location",
  "Lokalne preporuke": "Local recommendations",
  "Lokalni vodič": "Local guide",
  "Lozinka": "Password",
  "Lozinka je preslaba. Upotrijebite najmanje 8 znakova, sa slovima i brojevima.": "Password is too weak. Use at least 8 characters, with letters and numbers.",
  "Lozinka je promijenjena": "Password changed",
  "Lozinka je promijenjena.": "Password changed.",
  "Lozinka mora imati najmanje 8 znakova.": "Password must be at least 8 characters.",
  "Lozinka nije promijenjena": "Password was not changed",
  "Lozinke se ne podudaraju.": "Passwords do not match.",
  "Luk": "Arch",
  "Mijenjam…": "Changing…",
  "Mikrovalna": "Microwave",
  "Min. noći": "Min. nights",
  "Minimalno noćenja": "Minimum nights",
  "Mjesec": "Month",
  "Mjesečno": "Monthly",
  "Mjesta koja biste osobno preporučili svom gostu.": "Places you'd personally recommend to your guests.",
  "Mjesta su dodana ✓": "Places added ✓",
  "Mjesta u blizini": "Places nearby",
  "Moji objekti /": "My properties /",
  "Na dashboard": "To the dashboard",
  "Na javnoj stranici": "On the public page",
  "Na prijavu": "To login",
  "Na trenutnom planu ne možete dodati više objekata. Postojeći objekti i njihovi linkovi rade normalno.": "You can't add more properties on your current plan. Existing properties and their links keep working.",
  "Na što obratiti pažnju": "What needs attention",
  "Nadogradi →": "Upgrade →",
  "Najdulji boravak": "Longest stay",
  "Najkraći razmak koji se smije popuniti": "Shortest gap that may be filled",
  "Najmanje 8 znakova.": "At least 8 characters.",
  "Najpopunjeniji od sljedećih 12 mj.": "Busiest of the next 12 mo.",
  "Najviše gostiju": "Max guests",
  "Napomena": "Note",
  "Napravi link": "Create link",
  "Napravi link za Booking i Airbnb": "Create a link for Booking and Airbnb",
  "Napravi link za gosta": "Create a guest link",
  "Napravi link za prvog gosta": "Create a link for your first guest",
  "Napravi link za čistačicu": "Create a cleaner link",
  "Napravi objavu": "Create a post",
  "Napravi objekt →": "Create property →",
  "Napravi pozivnicu": "Create invitation",
  "Napravi račun": "Create account",
  "Napravite objavu za Instagram, Facebook grupe ili WhatsApp — slika i tekst na jeziku vaših gostiju, iz vašeg kalendara.": "Create a post for Instagram, Facebook groups or WhatsApp — an image and text in your guests' language, from your calendar.",
  "Napravite račun.": "Create an account.",
  "Napraviti novi link? Stari odmah prestaje raditi — novi treba ponovno poslati čistačici.": "Create a new link? The old one stops working immediately — the new one has to be sent to the cleaner again.",
  "Napraviti novi link? Stari odmah prestaje raditi — novi treba ponovno zalijepiti u Booking i Airbnb.": "Create a new link? The old one stops working immediately — the new one has to be pasted into Booking and Airbnb again.",
  "Napusti ovaj objekt": "Leave this property",
  "Napustili ste objekt": "You left the property",
  "Napustiti objekt": "Leave property",
  "Naslovna": "Cover",
  "Naslovna postavljena ✓": "Cover set ✓",
  "Nastaje jedinstven link koji vrijedi do dan nakon odlaska.": "A unique link is created that's valid until the day after departure.",
  "Nastaje jedinstven link koji vrijedi do dan nakon odlaska. Ako upišete e-mail, gost sam dobije link 3 dana prije dolaska i zahvalu s molbom za ocjenu na dan odlaska; e-mail se briše 30 dana nakon odlaska. Telefon služi samo za slanje odavde i ne sprema se.": "A unique link is created that's valid until the day after departure. If you enter an e-mail, the guest automatically gets the link 3 days before arrival and a thank-you with a request for a rating on the day of departure; the e-mail is deleted 30 days after departure. The phone is used only to send from here and isn't saved.",
  "Nastaje jedinstven link koji vrijedi do dan nakon odlaska. Telefon i e-mail služe samo za slanje linka odavde i ne spremaju se.": "A unique link is created that's valid until the day after departure. Phone and e-mail are used only to send the link from here and aren't saved.",
  "Nastavi s Google računom": "Continue with Google",
  "Natrag": "Back",
  "Natrag na aplikaciju": "Back to the app",
  "Natrag na prijavu": "Back to login",
  "Naziv": "Name",
  "Naziv (npr. Sauna, Jacuzzi...)": "Name (e.g. Sauna, Jacuzzi...)",
  "Naziv i lokacija": "Name and location",
  "Naziv i lokacija prikazuju se na javnoj stranici.": "The name and location appear on the public page.",
  "Naziv mreže": "Network name",
  "Naziv objekta": "Property name",
  "Naziv objekta *": "Property name *",
  "Naziv, lokacija, opis, kontakt i izgled javne stranice.": "Name, location, description, contact and the look of the public page.",
  "Ne postoji račun s tim e-mailom.": "There's no account with this e-mail.",
  "Ne spremaj": "Don't save",
  "Ned": "Sun",
  "Nedostaje →": "Missing →",
  "Nema aktivnih objekata.": "No active properties.",
  "Nema dolazaka ni odlazaka u sljedećih 14 dana.": "No arrivals or departures in the next 14 days.",
  "Nema kratkih praznina u sljedećih 90 dana.": "No short gaps in the next 90 days.",
  "Nema najavljenih dolazaka": "No upcoming arrivals",
  "Nema novih upita. Gost ga šalje s javne stranice nakon što odabere termin.": "No new inquiries. A guest sends one from the public page after choosing dates.",
  "Nema objekta.": "No property.",
  "Nema odlazaka u sljedećih 30 dana": "No departures in the next 30 days",
  "Nema odlazaka u sljedećih 30 dana.": "No departures in the next 30 days.",
  "Nema otvaranja vodiča u ovom razdoblju.": "No guide opens in this period.",
  "Nema otvaranja vodiča.": "No guide opens.",
  "Nema pregleda.": "No views.",
  "Nema promjena": "No changes",
  "Nema rezultata za \"": "No results for \"",
  "Nema upita u ovom popisu.": "No inquiries in this list.",
  "Nema veze s poslužiteljem. Provjerite internet i pokušajte ponovno.": "Can't reach the server. Check your internet connection and try again.",
  "Nemate račun?": "Don't have an account?",
  "Neograničeno": "Unlimited",
  "Neograničeno fotografija": "Unlimited photos",
  "Nepoznato": "Unknown",
  "Neprevedeni tekst prevede se sam kad ga prvi gost otvori na tom jeziku.": "Untranslated text is translated automatically when the first guest opens it in that language.",
  "Nije postavljeno": "Not set",
  "Nije povezano": "Not connected",
  "Nije prevedeno": "Not translated",
  "Nije spremljeno:": "Not saved:",
  "Nije uspjelo": "Didn't work",
  "Niste prijavljeni.": "You're not logged in.",
  "Niste prijavljeni. Osvjezite stranicu.": "You're not logged in. Refresh the page.",
  "Njemački": "German",
  "Nova javna stranica teme zasad ne prikazuje. Odabir se sprema i vrijedit će kad se teme uključe.": "The new public page doesn't show themes yet. Your choice is saved and will apply once themes are switched on.",
  "Nova lozinka": "New password",
  "Nova lozinka mora se razlikovati od stare.": "The new password must be different from the old one.",
  "Nova lozinka — Odmoria": "New password — Odmoria",
  "Nova stranica je objavljena. Kopirajte linkove i podijelite ih.": "The new page is live. Copy the links and share them.",
  "Nove mogućnosti Odmorie i savjeti za više rezervacija, najviše jednom mjesečno.": "New Odmoria features and tips for more bookings, at most once a month.",
  "Novi": "New",
  "Novi link (stari prestaje raditi)": "New link (the old one stops working)",
  "Novi link je spreman": "The new link is ready",
  "Novi upit gosta, istek plana, problem sa sinkronizacijom kalendara.": "New guest inquiry, plan expiry, calendar sync problems.",
  "Novosti i savjeti": "News and tips",
  "Noći u mjesecu": "Nights in the month",
  "O objektu": "About the property",
  "Obavijesti": "Notifications",
  "Objava 4:5": "Post 4:5",
  "Objave": "Posts",
  "Objavljeno": "Published",
  "Objekt": "Property",
  "Objekt je napravljen": "Property created",
  "Objekt je objavljen": "The property is published",
  "Objekt može imati najviše 3 suradnika (uključujući pozivnice na čekanju).": "A property can have at most 3 collaborators (including pending invitations).",
  "Objekti": "Properties",
  "Oblik": "Format",
  "Obrazac u Odmoriji": "Odmoria form",
  "Obrisati podatke gostiju za ovaj boravak? (npr. nakon što ste ih prijavili u eVisitor)": "Delete the guest details for this stay? (e.g. after you've registered them in eVisitor)",
  "Obriši": "Delete",
  "Obriši ovu fotografiju?": "Delete this photo?",
  "Obriši podatke": "Delete details",
  "Obriši račun": "Delete account",
  "Ocjena": "Rating",
  "Ocjena obrisana": "Rating deleted",
  "Ocjene gostiju": "Guest ratings",
  "Ocjene gostiju još nisu uključene — u Supabaseu treba pokrenuti sql/add-reviews.sql.": "Guest ratings aren't switched on yet — in Supabase you need to run sql/add-reviews.sql.",
  "Ocjene koje gosti ostave u vodiču na kraju boravka.": "Ratings guests leave in the guide at the end of their stay.",
  "Od": "From",
  "Odaberite barem jednu vrstu sadržaja.": "Choose at least one type of content.",
  "Odaberite datume dolaska i odlaska.": "Choose arrival and departure dates.",
  "Odaberite opis koji najbolje odgovara objektu.": "Choose the description that fits your property best.",
  "Odaberite termin ili upišite datume dolaska i odlaska.": "Choose dates or enter arrival and departure dates.",
  "Odaberite što je gostu dostupno tijekom boravka.": "Choose what guests can use during their stay.",
  "Odakle dolaze noćenja": "Where the nights come from",
  "Odakle dolaze posjetitelji javne stranice i gosti koji otvaraju vodič.": "Where public page visitors and guests opening the guide come from.",
  "Odbaci": "Discard",
  "Odbij": "Decline",
  "Odbijen": "Declined",
  "Odbijeni": "Declined",
  "Odbiti upit? Nakon toga možete gostu jednim klikom javiti da termin nije slobodan.": "Decline the inquiry? Afterwards you can tell the guest in one click that the dates aren't free.",
  "Odgovor": "Answer",
  "Odgovori WhatsAppom": "Reply on WhatsApp",
  "Odgovori e-mailom": "Reply by e-mail",
  "Odgovori na pitanja koja gosti često postavljaju.": "Answers to questions guests often ask.",
  "Odjava": "Log out",
  "Odjava do": "Check-out until",
  "Odlasci u sljedećih 30 dana i izmjene gostiju istog dana.": "Departures in the next 30 days and same-day guest changeovers.",
  "Odlazak": "Departure",
  "Odlazak mora biti nakon dolaska.": "Departure must be after arrival.",
  "Odmoria ne obrađuje naplatu gosta.": "Odmoria doesn't process guest payments.",
  "Odustani": "Cancel",
  "Oglasnik": "Classifieds",
  "Online plaćanje (Stripe) još nije spojeno. Do tada nadogradnja ide preko kontakta.": "Online payment (Stripe) is not connected yet. Until then, upgrades go through contact.",
  "Online plaćanje još nije spojeno. Za promjenu plana pišite na": "Online payment isn't connected yet. To change your plan, write to",
  "Opis": "Description",
  "Opis ispod objave. Link u objavi nije klikabilan — stavite ga u opis profila, a u storyju dodajte naljepnicu „Link”.": "Caption under the post. Links in posts aren't clickable — put it in your profile bio, and add a “Link” sticker in stories.",
  "Oprema za bebe": "Baby equipment",
  "Osnovni podaci spremljeni ✓": "Basic details saved ✓",
  "Osnovno": "Basics",
  "Ostalo": "Other",
  "Ostani": "Stay",
  "Otkaži u portalu": "Cancel in the portal",
  "Otvaram plaćanje…": "Opening payment…",
  "Otvaram portal…": "Opening portal…",
  "Otvaranja vodiča": "Guide opens",
  "Otvaranja vodiča po satu": "Guide opens by hour",
  "Otvorena karta": "Map opened",
  "Otvori": "Open",
  "Otvori cijene": "Open prices",
  "Otvori dashboard": "Open dashboard",
  "Otvori dashboard →": "Open dashboard →",
  "Otvori izbornik": "Open menu",
  "Otvori javnu stranicu": "Open public page",
  "Otvori letak za ispis": "Open printable flyer",
  "Ova godina, po izvoru.": "This year, by source.",
  "Ova se fotografija ne može staviti u sliku (poslužitelj to ne dopušta), pa je pozadina u bojama Odmorije.": "This photo can't be placed in the image (the server doesn't allow it), so the background uses Odmoria's colours.",
  "Ovaj objekt je zaključan — nadogradi plan 🔒": "This property is locked — upgrade your plan 🔒",
  "Ovaj objekt ne pripada vašem računu.": "This property doesn't belong to your account.",
  "Ove godine još nema boravaka u kalendaru.": "No stays in the calendar yet this year.",
  "Ove godine u kalendaru još nema zauzetih noći.": "No booked nights in the calendar yet this year.",
  "Ovo je samo pregled.": "This is only a preview.",
  "Ovu pozivnicu je već prihvatio netko drugi. Zamolite vlasnika za novu.": "Someone else has already accepted this invitation. Ask the owner for a new one.",
  "Označite barem jedno mjesto.": "Tick at least one place.",
  "Označite slobodne i zauzete datume.": "Mark free and booked dates.",
  "Označite sve što je gostu dostupno u objektu.": "Tick everything guests can use in the property.",
  "Ožujak": "March",
  "Parking": "Parking",
  "Parking i dolazak": "Parking and arrival",
  "Partner": "Partner",
  "Paušalno (godišnje po krevetu)": "Flat rate (yearly per bed)",
  "Perilica posuđa": "Dishwasher",
  "Perilica rublja": "Washing machine",
  "Pet": "Fri",
  "Pećnica": "Oven",
  "Pitanje": "Question",
  "Plan mijenjate u Računu (Pretplata i limiti).": "You change your plan in Account (Subscription and limits).",
  "Planovi": "Plans",
  "Plaćanje je prekinuto. Ništa nije naplaćeno.": "Payment was cancelled. Nothing was charged.",
  "Plaćanje je prošlo. Plan se upravo ažurira…": "Payment went through. Your plan is updating now…",
  "Plaćanje nije pokrenuto.": "Payment didn't start.",
  "Plaćeni plan je istekao.": "Your paid plan has expired.",
  "Plaže": "Beaches",
  "Plaže, restorani, kafići, trgovine i ljekarna oko vašeg objekta. Označite što želite preporučiti — poslije ih možete urediti.": "Beaches, restaurants, cafés, shops and a pharmacy around your property. Tick what you'd like to recommend — you can edit them afterwards.",
  "Po noćenju": "Per night",
  "Po noćenju (po osobi)": "Per night (per person)",
  "Po satu u danu — kada su gosti najčešće na vezi.": "By hour of the day — when guests are most often online.",
  "Podaci gostiju": "Guest details",
  "Podaci gostiju —": "Guest details —",
  "Podaci obrisani": "Details deleted",
  "Podaci su vidljivi samo gostu s privatnim linkom.": "These details are visible only to a guest with the private link.",
  "Podaci za eVisitor i boravišna pristojba": "eVisitor details and tourist tax",
  "Podaci: ©": "Data: ©",
  "Podijelite javnu stranicu i privatni vodič.": "Share the public page and the private guide.",
  "Podijeli…": "Share…",
  "Pogledaj javnu stranicu": "View public page",
  "Pogledaj kako gost vidi vodič": "See how guests see the guide",
  "Pogledaj planove": "See plans",
  "Pogledaj stranicu": "View page",
  "Pogledaj upite": "View inquiries",
  "Pokazatelj": "Metric",
  "Poljski": "Polish",
  "Pomozite gostu da odmah razumije veličinu objekta.": "Help guests understand the size of the property at a glance.",
  "Pomozite gostu da se snađe od dolaska do odlaska.": "Help guests find their way from arrival to departure.",
  "Pon": "Mon",
  "Ponovite lozinku": "Repeat password",
  "Ponoćni bazen": "Midnight pool",
  "Ponuda je kopirana — zalijepite je u poruku ili objavu": "Offer copied — paste it into a message or a post",
  "Popis mjesta trenutno nije dostupan. Pokušajte za minutu.": "The list of places isn't available right now. Try again in a minute.",
  "Popunjenost": "Occupancy",
  "Popunjenost (sljedećih 30 dana)": "Occupancy (next 30 days)",
  "Popunjenost po mjesecima": "Occupancy by month",
  "Popunjenost po mjesecima, sljedećih 12 mjeseci": "Occupancy by month, next 12 months",
  "Popunjenost · sljedećih 30 dana": "Occupancy · next 30 days",
  "Portal nije dostupan.": "The portal isn't available.",
  "Portali osvježavaju uvezeni kalendar sami, obično svakih nekoliko sati.": "The portals refresh the imported calendar on their own, usually every few hours.",
  "Poruka dobrodošlice": "Welcome message",
  "Poruka domaćina": "Host's message",
  "Posjećenost": "Visits",
  "Posjećenost, upiti, popunjenost i praznine u kalendaru.": "Visits, inquiries, occupancy and calendar gaps.",
  "Poslali smo link za prijavu": "We've sent a login link to",
  "Postavi novu lozinku": "Set new password",
  "Postavi prvi objekt": "Set up your first property",
  "Postavite ga u smještaju kako bi vodič uvijek bio pri ruci.": "Place it in the accommodation so the guide is always at hand.",
  "Postavite objekt — Odmoria": "Set up your property — Odmoria",
  "Postavite očekivanja za ugodan boravak.": "Set expectations for a pleasant stay.",
  "Postavke pristojbe još nisu uključene — pokrenite sql/add-guest-registration.sql.": "Tourist tax settings aren't switched on yet — run sql/add-guest-registration.sql.",
  "Postavke računa": "Account settings",
  "Postavljam…": "Setting…",
  "Posteljina": "Bed linen",
  "Potvrda e-maila — Odmoria": "E-mail confirmation — Odmoria",
  "Potvrđujemo e-mail…": "Confirming your e-mail…",
  "Povezano": "Connected",
  "Poveži Booking.com i Airbnb kalendare.": "Connect your Booking.com and Airbnb calendars.",
  "Poveži kalendar": "Connect calendar",
  "Površina": "Size",
  "Povuci": "Withdraw",
  "Povucite fotografije ili kliknite za odabir": "Drag photos here or click to choose",
  "Povući pozivnicu? Link prestaje raditi.": "Withdraw the invitation? The link stops working.",
  "Pozivnica": "Invitation",
  "Pozivnica je spremna — link je kopiran. Pošaljite ga suradniku.": "The invitation is ready — the link is copied. Send it to your collaborator.",
  "Pozivnica nije valjana ili je povučena.": "The invitation isn't valid or has been withdrawn.",
  "Pozivnica povučena": "Invitation withdrawn",
  "Pošalji WhatsAppom": "Send via WhatsApp",
  "Pošalji ponovno": "Send again",
  "Pošalji upit": "Send inquiry",
  "Pošaljite gostu": "Send to the guest",
  "Pravi raspored s vašim podacima i vašim fotografijama.": "The real layout with your details and your photos.",
  "Pravila i FAQ": "Rules and FAQ",
  "Pravila privatnosti": "Privacy policy",
  "Pravilo": "Rule",
  "Praznine u kalendaru": "Gaps in the calendar",
  "Predloži mjesta u blizini": "Suggest places nearby",
  "Predstavite objekt": "Present your property",
  "Pregled": "Overview",
  "Pregled gosta": "Guest preview",
  "Pregled objekta": "Property overview",
  "Pregled slike za objavu": "Post image preview",
  "Pregled vodiča": "Guide preview",
  "Pregled — ovako gost vidi": "Preview — this is what the guest sees",
  "Pregledi": "Views",
  "Pregledi javne stranice": "Public page views",
  "Pregledi javne stranice po danu u tjednu.": "Public page views by day of the week.",
  "Pregledi javne stranice · 30 dana": "Public page views · 30 days",
  "Pregledi koje otvorite sami iz aplikacije ne broje se. Upiti i dijelovi vodiča bilježe se od rujna 2026.; bilježi se samo vrsta i vrijeme, bez podataka o posjetitelju.": "Views you open yourself from the app aren't counted. Inquiries and guide sections are recorded from September 2026; only the type and time are recorded, with no visitor data.",
  "Pregledi po danu u tjednu": "Views by day of the week",
  "Preglednik je blokirao novi prozor — dopustite skočne prozore za ovu stranicu": "The browser blocked the new window — allow pop-ups for this page",
  "Prekratka": "Too short",
  "Preporuke": "Recommendations",
  "Preporuke (plaže, restorani…)": "Recommendations (beaches, restaurants…)",
  "Preskoči na sadržaj": "Skip to content",
  "Preskoči postavljanje": "Skip setup",
  "Preskoči za sada →": "Skip for now →",
  "Pretplata": "Subscription",
  "Pretplata i limiti": "Subscription and limits",
  "Pretraži sadržaje (npr. klima, parking, bazen)...": "Search amenities (e.g. air conditioning, parking, pool)...",
  "Preusmjeravamo vas na dashboard…": "Redirecting you to the dashboard…",
  "Preuzimam…": "Importing…",
  "Preuzmi": "Import",
  "Preuzmi CSV": "Download CSV",
  "Preuzmi QR kod (PNG)": "Download QR code (PNG)",
  "Preuzmi sadržaj": "Import content",
  "Preuzmi sadržaj iz drugog objekta": "Import content from another property",
  "Preuzmi sliku": "Download image",
  "Preuzmite QR kod kao PNG i dodajte ga u karticu dobrodošlice ili okvir u objektu.": "Download the QR code as a PNG and add it to a welcome card or a frame in the property.",
  "Prevedeno": "Translated",
  "Previše pokušaja. Pričekajte minutu pa pokušajte ponovno.": "Too many attempts. Wait a minute and try again.",
  "Prevodim — može potrajati do pola minute…": "Translating — this can take up to half a minute…",
  "Prezime": "Last name",
  "Prihvati i napravi link": "Accept and create link",
  "Prihvaćen": "Accepted",
  "Prihvaćeni": "Accepted",
  "Prijava": "Log in",
  "Prijava linkom na e-mail": "Log in with an e-mail link",
  "Prijava nije uspjela": "Login failed",
  "Prijava od": "Check-in from",
  "Prijava — Odmoria": "Log in — Odmoria",
  "Prijavi se": "Log in",
  "Prijavite se": "Log in",
  "Prijavite se da uredite objekt, kalendar i boravke.": "Log in to edit your property, calendar and stays.",
  "Prijavite se ili napravite račun da prihvatite poziv za suradnju na objektu.": "Log in or create an account to accept the invitation to collaborate on a property.",
  "Prijevod je spremljen": "Translation saved",
  "Prijevode trenutačno nije moguće učitati. Pokušajte ponovno za minutu.": "Translations can't be loaded right now. Try again in a minute.",
  "Prijevodi": "Translations",
  "Prijevodi još nisu uključeni: u Supabaseu treba pokrenuti sql/add-translations.sql, a u Vercelu postaviti SUPABASE_SERVICE_ROLE_KEY i ANTHROPIC_API_KEY (docs/odluke.md, točka 18).": "Translations aren't switched on yet: in Supabase you need to run sql/add-translations.sql, and in Vercel set SUPABASE_SERVICE_ROLE_KEY and ANTHROPIC_API_KEY (docs/odluke.md, point 18).",
  "Prijevodi za goste": "Translations for guests",
  "Prijevoz": "Transport",
  "Prikaz cijene": "Price display",
  "Prikazuje se samo na privatnom linku gosta — nikad na javnoj stranici.": "Shown only on the guest's private link — never on the public page.",
  "Prikaži": "Show",
  "Prikaži kao tablicu": "Show as table",
  "Prikaži lozinku": "Show password",
  "Prilagođeni sadržaji": "Custom amenities",
  "Pripremam letak…": "Preparing the flyer…",
  "Pristup za invalide": "Wheelchair access",
  "Privatni vodič": "Private guide",
  "Privatni vodič dobiva svaki gost posebno, s datumima boravka — šifre se otključaju sat prije njegovog dolaska.": "Each guest gets their own private guide with the dates of their stay — codes unlock an hour before they arrive.",
  "Privatni vodič za goste": "Private guest guide",
  "Privatno": "Private",
  "Privatno (samo vama)": "Private (only you)",
  "Pro": "Pro",
  "Procjena koristi cijenu po noći iz postavki; stvarni iznos ovisi o dogovoru s gostom i o platformi.": "The estimate uses the price per night from your settings; the actual amount depends on your agreement with the guest and on the platform.",
  "Procjena prihoda": "Revenue estimate",
  "Profil": "Profile",
  "Profil i sigurnost": "Profile and security",
  "Profil je spremljen.": "Profile saved.",
  "Promijeni lozinku": "Change password",
  "Promijeni u portalu": "Change in the portal",
  "Promjena lozinke": "Change password",
  "Promjena plana:": "Plan change:",
  "Promjene su odbačene": "Changes discarded",
  "Prosinac": "December",
  "Prosječan boravak": "Average stay",
  "Prosječna ocjena": "Average rating",
  "Provjeravam…": "Checking…",
  "Provjerite e-mail": "Check your e-mail",
  "Prva fotografija je naslovna — nju gost vidi prvu. Možete preskočiti i dodati ih kasnije.": "The first photo is the cover — it's what guests see first. You can skip this and add them later.",
  "Prva je naslovna · JPG ili PNG do 5 MB": "The first one is the cover · JPG or PNG up to 5 MB",
  "Puno ime": "Full name",
  "Pušenje nije dopušteno u objektu": "No smoking inside the property",
  "QR kod i adresa na slici vode na vašu javnu stranicu. Instagram u objavi ne otvara linkove — zato ih slika nosi.": "The QR code and address on the image lead to your public page. Instagram doesn't open links in posts — that's why the image carries them.",
  "QR kod nije spreman": "The QR code isn't ready",
  "QR kod za javnu stranicu": "QR code for the public page",
  "QR trenutno nije dostupan": "QR isn't available right now",
  "Raspored je kopiran": "Schedule copied",
  "Raspored čišćenja": "Cleaning schedule",
  "Raspored čišćenja —": "Cleaning schedule —",
  "Razdoblje": "Period",
  "Razdoblje plaćanja": "Billing period",
  "Razglednica": "Postcard",
  "Razmaci kraći od ovoga neće se ponuditi gostu. Na primjer, uz 3 — praznina od jedne ili dvije noći ostaje slobodna, a praznina od tri noći se nudi.": "Gaps shorter than this won't be offered to guests. For example, with 3 — a one- or two-night gap stays free, and a three-night gap is offered.",
  "Račun": "Account",
  "Račun je aktivan. Sljedeći korak: postavite svoj prvi objekt.": "Your account is active. Next step: set up your first property.",
  "Račun je na besplatnoj razini; objekti iznad limita su zaključani dok se plan ne obnovi. Podaci se ne brišu.": "Your account is on the free tier; properties above the limit are locked until the plan is renewed. No data is deleted.",
  "Račun je napravljen. Poslali smo link za potvrdu na": "Your account has been created. We've sent a confirmation link to",
  "Račun otvoren": "Account opened",
  "Račun s tim e-mailom već postoji. Prijavite se ili zatražite link za novu lozinku.": "An account with this e-mail already exists. Log in or request a link for a new password.",
  "Račun — Odmoria": "Account — Odmoria",
  "Recenzija je opet javna": "The review is public again",
  "Recenzija je sakrivena": "The review is hidden",
  "Recenzije": "Reviews",
  "Recite nam nešto o objektu": "Tell us about your property",
  "Registracija nije uspjela": "Sign-up failed",
  "Registracija trenutačno nije otvorena.": "Sign-up is not open at the moment.",
  "Registracija — Odmoria": "Sign up — Odmoria",
  "Registriraj se ponovno": "Sign up again",
  "Registrirajte se": "Sign up",
  "Restoran": "Restaurant",
  "Restorani": "Restaurants",
  "Rezervacija": "Booking",
  "Rezervacija je napravljena, ali upit nije označen:": "The booking was created, but the inquiry wasn't marked:",
  "Rezervacija je spremljena, ali automatski e-mail gostu još nije uključen (sql/add-guest-emails.sql).": "The booking was saved, but automatic e-mail to guests isn't switched on yet (sql/add-guest-emails.sql).",
  "Rezervacija je spremljena, ali kalendar nije ažuriran:": "The booking was saved, but the calendar wasn't updated:",
  "Rezervacija kreirana ✓": "Booking created ✓",
  "Rezervacija obrisana": "Booking deleted",
  "Rezervacija s linkom (ime gosta)": "Booking with a link (guest name)",
  "Rezervacija u Odmoriji": "Booking in Odmoria",
  "Rezervacije": "Bookings",
  "Rezervacije koje dogovorite izravno i dani koje ručno zatvorite moraju se zatvoriti i na portalima, inače se isti termin može prodati dvaput. Zalijepite link u Booking i Airbnb — oni ga sami čitaju svakih nekoliko sati. Link nosi samo datume, bez imena gostiju.": "Bookings you arrange directly and days you block manually must be closed on the portals too, otherwise the same dates can be sold twice. Paste the link into Booking and Airbnb — they read it on their own every few hours. The link carries only dates, no guest names.",
  "Rezerviraj izravno": "Book direct",
  "Roštilj": "Barbecue",
  "Rujan": "September",
  "Ručnici": "Towels",
  "Ručno": "Manual",
  "Ručno označeno": "Marked manually",
  "Sada": "Now",
  "Sada ste suradnik na objektu": "You're now a collaborator on the property",
  "Sadržaj je preuzet ✓": "Content imported ✓",
  "Sadržaji": "Amenities",
  "Sadržaji (bazen, klima…)": "Amenities (pool, air conditioning…)",
  "Sadržaji objekta": "Property amenities",
  "Sadrži dolazak, Wi-Fi i druge privatne informacije.": "Contains arrival, Wi-Fi and other private information.",
  "Sakrij": "Hide",
  "Sakrij lozinku": "Hide password",
  "Sakriveno s javne stranice": "Hidden from the public page",
  "Samo na privatnom linku gosta — nikad na javnoj stranici.": "Only on the guest's private link — never on the public page.",
  "Samo na privatnom linku gosta.": "Only on the guest's private link.",
  "Sef": "Safe",
  "Sef je desno od ulaza…": "The key safe is to the right of the entrance…",
  "Sef za ključeve je desno od ulaza…": "The key safe is to the right of the entrance…",
  "Sesija je istekla. Prijavite se ponovno.": "Your session expired. Please log in again.",
  "Sigurno za dijeljenje na društvenim mrežama i oglasima.": "Safe to share on social media and in ads.",
  "Sigurnosne kamere (vanjske)": "Security cameras (outdoor)",
  "Siječanj": "January",
  "Sinkronizacija kalendara": "Calendar sync",
  "Sinkronizacija nije uspjela (": "Sync failed (",
  "Sinkronizacija nije uspjela:": "Sync failed:",
  "Sinkronizacija pokrenuta...": "Sync started...",
  "Sinkronizacija u tijeku...": "Sync in progress...",
  "Sinkroniziraj": "Sync",
  "Sinkronizirano": "Synced",
  "Slika i tekst za Instagram, Facebook grupe, WhatsApp i oglase — iz podataka vašeg objekta, na jeziku vaših gostiju. Preuzmite i objavite.": "An image and text for Instagram, Facebook groups, WhatsApp and ads — from your property's details, in your guests' language. Download and post.",
  "Slika još nije spremna": "The image isn't ready yet",
  "Sljedeći dolazak": "Next arrival",
  "Sljedeći koraci": "Next steps",
  "Sljedećih 14 dana": "Next 14 days",
  "Slobodni termini": "Free dates",
  "Slobodno": "Available",
  "Složite galeriju koja predstavlja vaš objekt.": "Put together a gallery that presents your property.",
  "Soba": "Room",
  "Sobe": "Rooms",
  "Spavaća soba": "Bedroom",
  "Spavaće sobe": "Bedrooms",
  "Spavaćih soba": "Bedrooms",
  "Spol": "Sex",
  "Spremam…": "Saving…",
  "Spreman za ispis": "Ready to print",
  "Spremanje nije uspjelo:": "Saving failed:",
  "Spremi": "Save",
  "Spremi i dalje →": "Save and continue →",
  "Spremi i izračunaj": "Save and calculate",
  "Spremi i nastavi": "Save and continue",
  "Spremi i sinkroniziraj": "Save and sync",
  "Spremi prijevode": "Save translations",
  "Spremi promjene": "Save changes",
  "Spremite pristupne podatke za privatni vodič.": "Save the access details for the private guide.",
  "Spremiti promjene?": "Save changes?",
  "Spremljeno": "Saved",
  "Spremljeno ✓": "Saved ✓",
  "Spremljeno.": "Saved.",
  "Sri": "Wed",
  "Srpanj": "July",
  "Stavke se": "Items are",
  "Stigao je novi upit gosta": "A new guest inquiry has arrived",
  "Stiglo je": "Received",
  "Stopa upita": "Inquiry rate",
  "Story 9:16": "Story 9:16",
  "Studeni": "November",
  "Studio": "Studio",
  "Stupac „": "The column “",
  "Sub": "Sat",
  "Suradnici": "Collaborators",
  "Suradnici još nisu uključeni — u Supabaseu treba pokrenuti": "Collaborators aren't switched on yet — in Supabase you need to run",
  "Suradnik uklonjen": "Collaborator removed",
  "Suvlasnik, član obitelji ili agencija mogu uređivati ovaj objekt sa svojim računom: sadržaj, kalendar, rezervacije i upite. Pretplatu i suradnike vodite samo vi.": "A co-owner, family member or agency can edit this property with their own account: content, calendar, bookings and inquiries. Only you manage the subscription and collaborators.",
  "Sušilica rublja": "Tumble dryer",
  "Sva pronađena mjesta već su u vašim preporukama.": "All places found are already in your recommendations.",
  "Svaki gost dobiva svoj link, s datumima boravka: šifra vrata i Wi-Fi otključaju se sat prije njegovog dolaska, a link istječe dan nakon odlaska. Napravite ga kad potvrdite rezervaciju.": "Each guest gets their own link with the dates of their stay: the door code and Wi-Fi unlock an hour before they arrive, and the link expires the day after they leave. Create it when you confirm a booking.",
  "Svaki objekt dobiva vlastitu javnu stranicu i privatni link za goste.": "Each property gets its own public page and a private link for guests.",
  "Svaki podatak uređujete u aplikaciji kad god želite.": "You can edit every detail in the app whenever you like.",
  "Sve je u redu": "All good",
  "Sve možete promijeniti kasnije": "You can change everything later",
  "Sve za dolazak": "Everything for your arrival",
  "Svi": "All",
  "Svi vaši objekti, zadnjih 30 dana i sljedećih 30 dana.": "All your properties, the last 30 days and the next 30 days.",
  "Svibanj": "May",
  "Ta vrsta prijave trenutačno nije uključena.": "This sign-in method isn't enabled at the moment.",
  "Talijanski": "Italian",
  "Tekst kopiran": "Text copied",
  "Telefon": "Phone",
  "Telefon gosta": "Guest's phone",
  "Tema javne stranice": "Public page theme",
  "Tema ne mijenja samo boju. Svaka drugačije slaže zaglavlje i vodi s drugom informacijom — cijenom, istaknutom brojkom, popisom prostorija, pismom.": "A theme doesn't just change colours. Each one lays out the header differently and leads with different information — price, a highlight figure, a list of rooms, a letter.",
  "Tema nije spremljena da se taj podatak ne izgubi — javi vrijednost pa da se": "The theme wasn't saved so that this value isn't lost — report the value so the",
  "Tema spremljena ✓": "Theme saved ✓",
  "Temperatura bazena · danas": "Pool temperature · today",
  "Terakota": "Terracotta",
  "Terasa": "Terrace",
  "Termin": "Dates",
  "Termin je slobodan": "The dates are free",
  "Testni način — ništa se ne naplaćuje": "Test mode — nothing is charged",
  "Testni način:": "Test mode:",
  "Tjedan od": "Week of",
  "To mjesto nije pronađeno. Upišite mjesto ili ulicu drukčije (npr. „Vodice, Hrvatska”).": "That place wasn't found. Try writing the place or street differently (e.g. “Vodice, Croatia”).",
  "Topla voda": "Hot water",
  "Točna adresa": "Exact address",
  "Trajno i nepovratno: brišu se svi objekti, linkovi, rezervacije, recenzije i podaci gostiju. Privatni linkovi gostiju prestaju raditi. Ako plaćate karticom, prvo otkažite pretplatu.": "Permanent and irreversible: all properties, links, bookings, reviews and guest data are deleted. Guests' private links stop working. If you pay by card, cancel your subscription first.",
  "Trajno obrisati ovaj upit i gostove podatke?": "Permanently delete this inquiry and the guest's details?",
  "Trajno obrisati ovu ocjenu?": "Permanently delete this rating?",
  "Trajno obriši ovu rezervaciju?": "Permanently delete this booking?",
  "Travanj": "April",
  "Traži": "Search",
  "Tražim…": "Searching…",
  "Trenutačno uređujete": "Currently editing",
  "Trenutni plan": "Current plan",
  "Trgovine": "Shops",
  "U blizini nije pronađeno ništa. Pokušajte s većim mjestom.": "Nothing was found nearby. Try a larger place.",
  "U ovom dijelu imate promjene koje još nisu spremljene.": "You have changes in this section that haven't been saved yet.",
  "U sljedećih 90 dana nema slobodnog niza od": "In the next 90 days there's no free run of",
  "Udaljenost": "Distance",
  "Ukloni": "Remove",
  "Ukloni ovaj sadržaj?": "Remove this amenity?",
  "Ukloni ovu stavku?": "Remove this item?",
  "Ukloniti suradnika? Pristup objektu prestaje odmah.": "Remove the collaborator? Their access to the property ends immediately.",
  "Uklonjen": "Removed",
  "Uklonjeno": "Removed",
  "Ulica i broj, grad": "Street and number, town",
  "Upit": "Inquiry",
  "Upit prihvaćen — pošaljite gostu link ✓": "Inquiry accepted — send the guest the link ✓",
  "Upit za": "Inquiry for",
  "Upiti": "Inquiries",
  "Upiti gostiju": "Guest inquiries",
  "Upiti po kanalu": "Inquiries by channel",
  "Upiti s javne stranice — prihvatite ih i pošaljite link u jednom koraku.": "Inquiries from the public page — accept them and send the link in one step.",
  "Upiti se još ne spremaju. Kad se u Supabaseu pokrene sql/add-inquiries.sql, gosti će s vaše javne stranice moći poslati upit s imenom i kontaktom, a vi ćete ga vidjeti ovdje.": "Inquiries aren't saved yet. Once sql/add-inquiries.sql is run in Supabase, guests will be able to send an inquiry with their name and contact from your public page, and you'll see it here.",
  "Upiti · 30 dana": "Inquiries · 30 days",
  "Upiši datume.": "Enter the dates.",
  "Upišite adresu ili mjesto.": "Enter an address or a place.",
  "Upišite e-mail i lozinku.": "Enter your e-mail and password.",
  "Upišite e-mail na koji ćemo poslati link za prijavu.": "Enter the e-mail we should send the login link to.",
  "Upišite e-mail računa — poslat ćemo link za novu lozinku.": "Enter your account's e-mail — we'll send a link for a new password.",
  "Upišite grad ili mjesto koje gost prepoznaje.": "Enter the town or place a guest will recognise.",
  "Upišite ime i prezime gosta — vidi ga u pozdravu vodiča.": "Enter the guest's full name — they see it in the guide's greeting.",
  "Upišite ime i prezime gosta.": "Enter the guest's full name.",
  "Upišite naziv objekta.": "Enter the property name.",
  "Upišite novu lozinku za svoj Odmoria račun.": "Enter a new password for your Odmoria account.",
  "Upišite to prije dolaska — vodič se otključa sat vremena prije prijave.": "Add it before arrival — the guide unlocks an hour before check-in.",
  "Upload greška:": "Upload error:",
  "Upload nije uspio": "Upload failed",
  "Upload nije uspio:": "Upload failed:",
  "Upravljaj pretplatom": "Manage subscription",
  "Upravljaj pretplatom (kartica, računi, otkaz)": "Manage subscription (card, invoices, cancel)",
  "Upravljajte planom i naplatom.": "Manage your plan and billing.",
  "Upute (prijava, odjava, parking, uređaji)": "Instructions (check-in, check-out, parking, appliances)",
  "Upute spremljene ✓": "Instructions saved ✓",
  "Upute za dolazak": "Arrival instructions",
  "Upute za korištenje": "How to use things",
  "Upute za odlazak": "Departure instructions",
  "Uredi": "Edit",
  "Uređivanje objekta": "Editing property",
  "Uskoro.": "Coming soon.",
  "Usporedba objekata": "Compare properties",
  "Usporedba svih objekata i pregled cijele godine.": "Comparison of all properties and an overview of the whole year.",
  "Usporedba trenutno nije dostupna.": "Comparison isn't available right now.",
  "Uto": "Tue",
  "Uvjete korištenja": "Terms of use",
  "Učitavam…": "Loading…",
  "Učitavanje...": "Loading...",
  "Učitavanje…": "Loading…",
  "Vaš boravak": "Your stay",
  "Vaš boravak —": "Your stay —",
  "Vaš ispravak": "Your correction",
  "Vaš plan": "Your plan",
  "Vaš popust": "Your discount",
  "Vaša poruka dobrodošlice.": "Your welcome message.",
  "Vaše ime": "Your name",
  "Vaše ime (domaćin)": "Your name (host)",
  "Vaše preporuke, prijevoz i izleti — gost ih vidi u vodiču i na javnoj stranici.": "Your recommendations, transport and trips — guests see them in the guide and on the public page.",
  "Vaši ispravci": "Your corrections",
  "Vaši linkovi": "Your links",
  "Vaši linkovi rade i promjene se prikazuju odmah nakon spremanja.": "Your links work and changes show up as soon as you save.",
  "Vaši linkovi su spremni": "Your links are ready",
  "Vaši zauzeti dani prema Bookingu i Airbnbu": "Your booked days for Booking and Airbnb",
  "Važne obavijesti": "Important notifications",
  "Veljača": "February",
  "Već imate račun?": "Already have an account?",
  "Vidikovac": "Viewpoint",
  "Villa": "Villa",
  "Više": "More",
  "Više: objekti, pretplata, račun": "More: properties, subscription, account",
  "Vodič": "Guide",
  "Vodič i javna stranica prikazuju se gostu na njegovom jeziku. Vaše tekstove Odmoria prevodi automatski — ovdje ih pregledajte i ispravite. Vaš ispravak vide samo gosti ovog objekta.": "The guide and public page are shown to guests in their own language. Odmoria translates your texts automatically — review and correct them here. Only guests of this property see your correction.",
  "Vodič je 0% gotov": "Guide is 0% complete",
  "Vodič tada više ne pokazuje šifre, ali se i dalje otvara. Deaktivirajte link kad gost ode.": "The guide no longer shows codes then, but it still opens. Deactivate the link when the guest leaves.",
  "Vodič za goste": "Guest guide",
  "Vraćen automatski prijevod": "Automatic translation restored",
  "Vrijednost": "Value",
  "Vrijeme dolaska i odlaska": "Arrival and departure times",
  "Vrsta": "Type",
  "Vrsta isprave": "Document type",
  "Vrsta objekta": "Property type",
  "Vrsta smještaja": "Accommodation type",
  "Vrt": "Garden",
  "WhatsApp": "WhatsApp",
  "WhatsApp broj": "WhatsApp number",
  "WhatsApp status": "WhatsApp status",
  "WhatsApp, e-mail ili kopirana poruka": "WhatsApp, e-mail or copied message",
  "WhatsApp, e-mail, kopirana poruka": "WhatsApp, e-mail, copied message",
  "WhatsAppom": "via WhatsApp",
  "Wi-Fi i kuća": "Wi-Fi and house",
  "Wi-Fi lozinka": "Wi-Fi password",
  "Wi-Fi lozinka i kod vrata se ne prikazuju u pregledu — vidljivi su gostu tek 1h prije dolaska.": "The Wi-Fi password and door code aren't shown in the preview — guests see them only 1 hour before arrival.",
  "Wi-Fi lozinke": "Wi-Fi password",
  "Wi-Fi mreža": "Wi-Fi network",
  "Wi-Fi mreža —": "Wi-Fi network —",
  "Wi-Fi podaci spremljeni ✓": "Wi-Fi details saved ✓",
  "Wi-Fi pristup": "Wi-Fi access",
  "Wi-Fi za goste": "Wi-Fi for guests",
  "Za": "For",
  "Za Njuškalo, Index oglase i slične stranice.": "For Njuškalo, Index oglasi and similar sites.",
  "Za domaćine s do 5 objekata": "For hosts with up to 5 properties",
  "Za grupe o odmoru u Hrvatskoj — na jeziku grupe (npr. njemački za „Kroatien Urlaub”).": "For groups about holidays in Croatia — in the group's language (e.g. German for “Kroatien Urlaub”).",
  "Za još jedan objekt treba viša razina.": "Another property needs a higher plan.",
  "Za potvrdu upišite: obriši račun": "To confirm, type: obriši račun",
  "Za potvrđenog gosta": "For a confirmed guest",
  "Za profesionalce i timove": "For professionals and teams",
  "Za promociju": "For promotion",
  "Za prvi digitalni vodič": "For your first digital guide",
  "Zaboravili ste lozinku?": "Forgot your password?",
  "Zabranjeno pušenje": "No smoking",
  "Zadnja sinkronizacija:": "Last sync:",
  "Zatim vas vodimo kroz postavljanje prvog objekta.": "Then we'll guide you through setting up your first property.",
  "Zatvori": "Close",
  "Zauzete noći iz kalendara (ručno, rezervacije, Booking.com, Airbnb) za sljedećih 12 mjeseci.": "Booked nights from the calendar (manual, bookings, Booking.com, Airbnb) for the next 12 months.",
  "Zauzeti termini s Bookinga i Airbnba ulaze u vaš kalendar i tamo se zaključavaju. Kalendari se osvježavaju sami (automatska sinkronizacija); gumbom ih osvježite odmah.": "Dates booked on Booking and Airbnb come into your calendar and are locked there. Calendars refresh on their own (automatic sync); use the button to refresh them now.",
  "Zauzetih noći": "Booked nights",
  "Zauzeto": "Booked",
  "Zauzeto ručno": "Blocked manually",
  "Zlatni sat": "Golden hour",
  "bez datuma": "no dates",
  "bez linka": "no link",
  "bez pretplate": "no subscription",
  "bez provizije": "no commission",
  "boravak": "stay",
  "boravaka": "stays",
  "boravka": "stays",
  "cijenom": "the price",
  "dan": "day",
  "dana": "days",
  "do 15 objekata · 50 fotografija po objektu": "up to 15 properties · 50 photos per property",
  "do 5 objekata · 30 fotografija po objektu": "up to 5 properties · 30 photos per property",
  "dodaju": "added",
  "domaćin": "host",
  "foto dodano ✓": "photo added ✓",
  "fotografija": "photos",
  "fotografije": "photos",
  "godišnje ·": "yearly ·",
  "gost": "guest",
  "gosta": "guests",
  "gosti koji traže lokaciju": "guests looking for the location",
  "gosti s privatnim linkom": "guests with a private link",
  "gostiju": "guests",
  "iCal sinkronizacija": "iCal sync",
  "ili": "or",
  "ili više.": "or more.",
  "imaju prednost pred automatskim": "take precedence over automatic ones",
  "imenom kao plakatom": "the name as a poster",
  "imenom objekta": "the property name",
  "javne i ne sakrivene": "public and not hidden",
  "je objavljen": "is published",
  "je prevelika": "is too large",
  "jutarnje sunce": "morning sun",
  "jučer": "yesterday",
  "kol": "Aug",
  "kratka praznina": "short gap",
  "kratke praznine": "short gaps",
  "kratkih praznina": "short gaps",
  "limit plana": "plan limit",
  "link je još aktivan": "link is still active",
  "link poslan": "link sent",
  "link prije dolaska": "link before arrival",
  "linka su još aktivna": "links are still active",
  "linkova je još aktivno": "links are still active",
  "lip": "Jun",
  "lis": "Oct",
  "mjesec": "month",
  "mjeseca": "months",
  "mjeseci": "months",
  "mjesečno": "monthly",
  "m² ukupno": "m² in total",
  "ned": "Sun",
  "neograničeno": "unlimited",
  "neograničeno fotografija": "unlimited photos",
  "neograničeno objekata": "unlimited properties",
  "ni $1": "or $1",
  "ništa se stvarno ne naplaćuje. Za probu upišite karticu": "nothing is actually charged. To test, enter the card",
  "ništa se stvarno ne naplaćuje. Za probu: kartica": "nothing is actually charged. To test: card",
  "nova upita": "new inquiries",
  "nova upita gostiju": "new guest inquiries",
  "novi upit": "new inquiry",
  "novi upit gosta": "new guest inquiry",
  "novih upita": "new inquiries",
  "novih upita gostiju": "new guest inquiries",
  "novo": "new",
  "noć": "night",
  "noć je": "night is",
  "noći": "nights",
  "noći je": "nights are",
  "noći su": "nights are",
  "npr. Ana": "e.g. Ana",
  "npr. Apartman Sunce, Villa Mare": "e.g. Apartment Sunce, Villa Mare",
  "npr. Hvar, Hrvatska": "e.g. Hvar, Croatia",
  "npr. Marko — suvlasnik": "e.g. Marko — co-owner",
  "npr. Mjesto 4, ispred zgrade": "e.g. Space 4, in front of the building",
  "npr. Split, Hrvatska": "e.g. Split, Croatia",
  "npr. Villa Luna, Apartman Ana": "e.g. Villa Luna, Apartment Ana",
  "objekata": "properties",
  "objekt": "property",
  "objekta": "properties",
  "od 5, sve ocjene": "out of 5, all ratings",
  "odrasla osoba": "adult",
  "odrasle osobe": "adults",
  "odraslih osoba": "adults",
  "opcionalno": "optional",
  "osoba": "people",
  "ovaj objekt": "this property",
  "ožu": "Mar",
  "ožujak": "March",
  "pet": "Fri",
  "pismom domaćice": "the host's letter",
  "po danu": "per day",
  "po mjesecu": "per month",
  "po noći": "per night",
  "po osobi po noći, ili po krevetu godišnje": "per person per night, or per bed per year",
  "po tjednu": "per week",
  "pogled na luku": "harbour view",
  "pon": "Mon",
  "popisom prostorija": "a list of rooms",
  "postojećima u": "to the existing ones in",
  "praznina je kraća": "gap is shorter",
  "praznina je kraće": "gaps are shorter",
  "praznine su kraće": "gaps are shorter",
  "prazno": "empty",
  "prema prethodnom razdoblju": "compared with the previous period",
  "privatno": "private",
  "pro": "Dec",
  "provjerite vezu": "check your connection",
  "prvi mjesec": "first month",
  "rezervacija u Odmoriji": "booking in Odmoria",
  "ruj": "Sep",
  "ručno označeno": "marked manually",
  "s adrese svog računa.": "from your account's address.",
  "samom slikom": "the photo alone",
  "sat": "hour",
  "sata": "hours",
  "sati": "hours",
  "sij": "Jan",
  "siječanj": "January",
  "slika preskočena": "image skipped",
  "slika preskočeno": "images skipped",
  "sri": "Wed",
  "srp": "Jul",
  "stu": "Nov",
  "stupac razriješi (vidi sql/add-theme-to-properties.sql).": "column can be resolved (see sql/add-theme-to-properties.sql).",
  "sub": "Sat",
  "suradnici": "contributors",
  "sve je prevedeno": "everything is translated",
  "sve je već ispunjeno": "everything is already filled in",
  "svi": "May",
  "tablicom podataka": "a data table",
  "temperaturom bazena": "the pool temperature",
  "termin je prošao": "the dates have passed",
  "tjedan": "week",
  "tjedna": "weeks",
  "tra": "Apr",
  "tuš, perilica": "shower, washing machine",
  "u odnosu na prethodnih 30 dana": "compared with the previous 30 days",
  "u tijeku": "in progress",
  "upit bez datuma": "inquiry without dates",
  "upit s javne stranice": "inquiry from the public page",
  "uto": "Tue",
  "velj": "Feb",
  "veljača": "February",
  "već postoji": "already exists",
  "višem od vašeg": "higher than yours",
  "vrijedi od": "valid from",
  "vrijednost · oznaka": "value · label",
  "za WhatsApp": "for WhatsApp",
  "za WhatsApp, pamti se na ovom uređaju": "for WhatsApp, remembered on this device",
  "za automatske poruke": "for automatic messages",
  "za slanje": "for sending",
  "zahvala na odlasku": "thank-you on departure",
  "zahvala poslana": "thank-you sent",
  "· dijeljeno": "· shared",
  "· neograničeno": "· unlimited",
  "· plaćanje kasni": "· payment overdue",
  "Čeka da otvori link": "Waiting for them to open the link",
  "Česta pitanja": "FAQ",
  "Čet": "Thu",
  "Četiri kartice na listu A4 s fotografijom, QR kodom i porukom „Sljedeći put rezervirajte izravno”. Ostavite ih u smještaju ili ih dajte gostima na odlasku — na jeziku odabranom gore.": "Four cards on an A4 sheet with a photo, QR code and the message “Next time, book direct”. Leave them in the accommodation or hand them to guests when they leave — in the language chosen above.",
  "Češki": "Czech",
  "čet": "Thu",
  "čišćenje između odlaska i dolaska": "cleaning between departure and arrival",
  "čišćenje mora stati između odjave i prijave": "cleaning has to fit between check-out and check-in",
  "člana tima": "team members",
  "članova tima": "team members",
  "Šifra vrata / sef": "Door code / key safe",
  "Šifra vrata / sef za ključeve": "Door code / key safe",
  "Šifra vrata i upute za dolazak — samo za potvrđene goste.": "Door code and arrival instructions — for confirmed guests only.",
  "Što gosti otvaraju u vodiču": "What guests open in the guide",
  "Što objavljujete": "What you're posting",
  "Što se događa ovih dana i na što obratiti pažnju.": "What's happening these days and what to keep an eye on.",
  "šifre vrata": "door code",
  "šifre vrata ni Wi-Fi lozinke": "a door code or Wi-Fi password",
  "— dostupan je u planu": "— available on the plan",
  "— koriste je teme Laguna i Ponoćni bazen": "— used by the Laguna and Midnight Pool themes",
  "— nije u vašem planu": "— not in your plan",
  "— otvorite ga, pa vas vodimo dalje.": "— open it and we'll take you further.",
  "” u bazi već sadrži „": "” in the database already contains “",
  "”, što nije ime teme.": "”, which isn't a theme name.",
  "€ / noć": "€ / night",
  "← Natrag": "← Back",
  "● Uživo": "● Live",
  "✓ Kopirano": "✓ Copied",
  "✓ Sve je spremljeno.": "✓ Everything is saved."
}

export const P = {
  ", {} nije ({})": ", {} not ({})",
  ", {} već postoji": ", {} already exist",
  "Bez poznate države: {} (stariji pregledi ili država koju Vercel ne prepozna).": "Without a known country: {} (older views or a country Vercel doesn't recognise).",
  "Check-in od {}": "Check-in from {}",
  "Check-out do {}": "Check-out until {}",
  "Do {} {}": "Until {} {}",
  "Dostupno u planu {}": "Available on the {} plan",
  "Foto {}": "Photo {}",
  "Fotografija {}": "Photo {}",
  "Godišnje · {}": "Yearly · {}",
  "Gost dolazi {}, a u vodiču nema {}": "A guest arrives {}, but the guide has no {}",
  "Hvala! Vaš plan je sada {}.": "Thank you! Your plan is now {}.",
  "Mjesečno · {}": "Monthly · {}",
  "Na planu {} iskoristili ste sve objekte ({} od {}). Za još jedan potrebna je viša razina. Postojeći objekti i njihovi linkovi rade normalno.": "On the {} plan you've used all your properties ({} of {}). Another one needs a higher plan. Existing properties and their links keep working.",
  "Na planu {} otvoreno je {} od {} tema.": "On the {} plan, {} of {} themes are unlocked.",
  "Najviše {} suradnika po objektu.": "At most {} collaborators per property.",
  "Nema pregleda s poznatom državom u zadnjih {}. Država se bilježi od uključivanja ove mogućnosti.": "No views with a known country in the last {}. The country is recorded from when this feature was switched on.",
  "Nema pregleda u zadnjih {}.": "No views in the last {}.",
  "Nema upita u zadnjih {}.": "No inquiries in the last {}.",
  "Npr. {} – {} ({}). Gosti ih ne mogu tražiti na javnoj stranici — uključite popunjavanje praznina.": "E.g. {} – {} ({}). Guests can't request them on the public page — turn on gap filling.",
  "Npr. {} – {} ({}). Ponudite je bivšim gostima ili na društvenim mrežama — slika i tekst su spremni u jednom kliku.": "E.g. {} – {} ({}). Offer it to past guests or on social media — the image and text are ready in one click.",
  "Objekt može imati najviše {} suradnika (uključujući pozivnice na čekanju). Za novog uklonite postojećeg ili povucite pozivnicu.": "A property can have at most {} collaborators (including pending invitations). To add a new one, remove an existing one or withdraw an invitation.",
  "Odaberi {}": "Choose {}",
  "Osoba {}n": "Person {}n",
  "Otvaranja vodiča, zadnjih {}": "Guide opens, last {}",
  "Ovo je dio analitike u planu {}.": "This is part of the analytics on the {} plan.",
  "Označeno: {} → {} ✓": "Marked: {} → {} ✓",
  "Označeno: {} ✓": "Marked: {} ✓",
  "Paušal: {} {} × {} = {} godišnje. Ovaj boravak ne mijenja iznos.": "Flat rate: {} {} × {} = {} per year. This stay doesn't change the amount.",
  "Plaćeni plan je istekao {}. {}.": "Your paid plan expired {}. {}.",
  "Pokretanje: {}": "Running: {}",
  "Početak: {} — odaberi zadnji datum": "Start: {} — choose the last date",
  "Pregledi javne stranice, zadnjih {}": "Public page views, last {}",
  "Prevedi što nedostaje ({})": "Translate what's missing ({})",
  "Prijevod: {}": "Translation: {}",
  "Prvi: {} – {} ({}, {}). Gost bez linka ne dobiva šifru ni upute.": "First: {} – {} ({}, {}). A guest without a link gets no code or instructions.",
  "Sinkronizirano {} datuma ✓ —": "Synced {} dates ✓ —",
  "Slobodno {}": "Free {}",
  "Slobodno {} ({})": "Free {} ({})",
  "Spremljeno prijevoda: {}": "Translations saved: {}",
  "Taj jezik nije u vašem planu{}.": "That language isn't in your plan{}.",
  "Tema {} je uključena u plan {}": "The {} theme is included in the {} plan",
  "Tema {} traži plan {}": "The {} theme needs the {} plan",
  "U tijeku: {}, odlazak {}": "In progress: {}, departure {}",
  "Učitavam {} od {}…": "Uploading {} of {}…",
  "Vodič je {}% gotov": "Guide is {}% complete",
  "Wi-Fi mreža {}": "Wi-Fi network {}",
  "Za {}": "For {}",
  "Zadnja sinkronizacija bila je prije {} {}": "The last sync was {} {} ago",
  "Zadnje ažurirao gost: {}. Podaci se brišu sami 30 dana nakon odlaska.": "Last updated by the guest: {}. The details are deleted automatically 30 days after departure.",
  "Zadnjih {}, {}. Obje serije na istoj skali.": "Last {}, {}. Both series on the same scale.",
  "do {} {}": "up to {} {}",
  "do {}. {}.": "until {}. {}.",
  "najmanje {} noći": "at least {} nights",
  "noći. Platforme: {}.": "nights. Platforms: {}.",
  "od {}": "from {}",
  "od {} do {}": "from {} to {}",
  "odlazak {} · {}": "departure {} · {}",
  "prije {} dan": "{} day ago",
  "prije {} dana": "{} days ago",
  "prije {} h": "{} h ago",
  "prije {} min": "{} min ago",
  "prva {} mj.": "first {} mo.",
  "za {} dan": "in {} day",
  "za {} dana": "in {} days",
  "{} (noći × {})": "{} (nights × {})",
  "{} / {} fotografija · prva je naslovna": "{} / {} photos · the first one is the cover",
  "{} dodano — ostalo ({}) nije stalo u limit plana.": "{} added — the rest ({}) didn't fit in your plan's limit.",
  "{} dodano.": "{} added.",
  "{} fotografija": "{} photos",
  "{} gost": "{} guest",
  "{} gosta": "{} guests",
  "{} gostiju": "{} guests",
  "{} je objavljen": "{} is published",
  "{} još nije prevedeno": "{} not translated yet",
  "{} krevet": "{} bed",
  "{} kreveta": "{} beds",
  "{} min autom": "{} min by car",
  "{} min pješice": "{} min walk",
  "{} m² ukupno": "{} m² in total",
  "{} nije uključen u vaš plan{}. Gosti tada vide stranicu na engleskom.{}": "{} isn't included in your plan{}. Guests then see the page in English.{}",
  "{} nova upita gostiju": "{} new guest inquiries",
  "{} novi upit gosta": "{} new guest inquiry",
  "{} novih upita gostiju": "{} new guest inquiries",
  "{} noć": "{} night",
  "{} noći": "{} nights",
  "{} objekata": "{} properties",
  "{} objekt": "{} property",
  "{} objekta": "{} properties",
  "{} objekt{} zaključano": "Locked properties: {1}",
  "{} od 12 do 18 god. (pola)": "{} aged 12 to 18 (half)",
  "{} od 30 noći zauzeto": "{} of 30 nights booked",
  "{} od 5": "{} out of 5",
  "{} od {} objekata iskorišteno · još {} {}": "{} of {} properties used · {} {} left",
  "{} odrasla": "{} adult",
  "{} odrasle": "{} adults",
  "{} odraslih": "{} adults",
  "{} plan uključuje {} {}. Nadogradite plan za više.": "The {} plan includes {} {}. Upgrade your plan for more.",
  "{} po objektu": "{} per property",
  "{} po osobi po noći — izračun čim gost upiše podatke.": "{} per person per night — calculated as soon as the guest enters their details.",
  "{} posjeta završi upitom": "{} of visits end with an inquiry",
  "{} preporuka": "{} recommendations",
  "{} soba": "{} bedrooms",
  "{} sobe": "{} bedrooms",
  "{} {} do 12 god. (ne plaća)": "{} {} under 12 (free)",
  "{} {} nakon odlaska gosta": "{} {} after the guest left",
  "{} {} od minimalnog boravka ({})": "{} {} than the minimum stay ({})",
  "{} {} s platformi nema link za vodič": "{} {} from platforms without a guide link",
  "{} {} u sljedećih 60 dana": "{} {} in the next 60 days",
  "{} {} u tom terminu već je zauzeto u kalendaru. Svejedno napraviti rezervaciju?": "{} {} in those dates already booked in the calendar. Create the booking anyway?",
  "{} {} u tom terminu već je zauzeto. Svejedno prihvatiti upit?": "{} {} in those dates already booked. Accept the inquiry anyway?",
  "{} {} već zauzeto": "{} {} already booked",
  "{} {} · neograničeno na planu {}": "{} {} · unlimited on the {} plan",
  "{} {} — prevelika ili preko limita plana.": "{} {} — too large or over the plan limit.",
  "{} · {} po objektu": "{} · {} per property",
  "{} – {} · prijaviti u eVisitor u roku 24 sata od dolaska": "{} – {} · register in eVisitor within 24 hours of arrival",
  "{} € / noć": "{} € / night",
  "{} €/god": "{} €/yr",
  "{} €/mj": "{} €/mo",
  "{} → {} ({} dana)": "{} → {} ({} days)",
  "{}. godina, zauzete noći po izvoru.": "{}, booked nights by source.",
  "{}/{} dovršeno": "{}/{} complete",
  "{}: odlazak{}": "{}: departure{}",
  "{}: {} datuma": "{}: {} dates",
  "{}: {} dodano": "{}: {} added",
  "{}suradnik od {}": "{}collaborator since {}",
  "{}{}. Prihvatite upit i gost odmah dobiva link za vodič.": "{}{}. Accept an inquiry and the guest gets the guide link straight away.",
  "· kraće od minimalnog boravka ({}){}": "· shorter than the minimum stay ({}){}",
  "— dostupan je u planu {}": "— available on the {} plan",
  "— {}, domaćin": "— {}, host"
}
